apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  volumes:
  - name: data-volume

  containers:
  - name: myapp-container
    image: nginx
    volumeMounts:
    - name: data-volume
      mountPath: /usr/share/nginx/html

  initContainers:
  - name: init-myservice
    image: busybox:1.28
    volumeMounts:
    - name: data-volume
      mountPath: /data
